### ISSUE TITLE
Topics with similar names

### ISSUE THREAD

**Issue by sunnyjindal** [the-canonizer/canonizer-3.0-api#1021]
Whenever the user tries to create a topic, after entering 3 alphabets, the system should start semantic search and return the list of topics that exists with the same name.

**Comment by nalwa** [comment]
As per discussion with team we are  keeping existing elastic search with search limit of 10 results. So in order to this there is no changes required in existing API from back-end side.

API which is already there is -   
https://api3.canonizer.com/api/v3/search?term=test&size=20&page=1&type=topic

Note: parameter size needs to be adjusted to 10 and it will server our purpose.
