### ISSUE TITLE
Display  total score in "support tree" from Tree coming from Service (Mongo DB)

### ISSUE THREAD

**Issue by nalwa** [the-canonizer/canonizer-3.0-api#443]
In case of big topics like "Theory of Consciousness"  total score API is taking more than 30 sec for "Mind Expert" Algorithm,

So  instead of calculating score again it should be fetched from "Tree coming from service" at front-end .

Related Ticket - https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/61

**Comment by shahab-ramzan** [comment]
In this ticket What I did is:
- Removed API call  (**camp-total-support-score**) for the total scores that were being used in the support tree for Total score
- Displayed score in support tree card for selected camp from camp tree 
- Handled 100% canonized score  check for support tree as well 
- Since the camp tree is already being updated based on filters and adding or removing the support to the camp. So, now the total updated scores for the selected camp are showing in the support card as well.

@nalwa Please let me know if anything else is needed in this ticket.

**Comment by rupalichavan9860** [comment]
Verified on live by @akuks
