### ISSUE TITLE
"GitHub" social login issue

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#562]
Steps to Reproduce

1. Go to canonizer3.canonizer.com and click on Login button
2. Click on GitHub icon to login with GitHub account
3. It will navigate to "Authorize Canonizer" page
4. Click on cancel button

Actual result: Instead of redirecting to canonizer3.canonizer.com, it is redirecting to canonizer.com

Expected Result: It must redirect to canonizer3.canonizer.com

https://www.awesomescreenshot.com/video/15047898?key=edc00e38359d6e0bd4f8160705c4db9f

**Comment by mark-shamy** [comment]
This part of a broader issue of hard URL references that should be replaced with URL from deployment config parameters

**Comment by ashish76** [comment]
@mark-shamy In the case of GitHub login we have to create one more app with the callback URL that redirects to the staging environment. Because there is no option to specify the multiple callbacks. I discussed this issue in the standup call. 

As we have already tested this on the local environment as well as in production. We can either ignore this issue or create a new GitHub app.  And then we can put that URL in the configuration as you suggested. 

Please suggest.

**Comment by ashish76** [comment]
As discussed with Mark in a weekly call, we can ignore this case for the staging environment.  
Because GitHub allows only one callback URL per app. We have already tested this on the local and production environments and it is working fine, so we close this issue.
