### ISSUE TITLE
Admin Hot Topic Control

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-api#568]
Create admin control to change the "Hot Topic" on the homepage that takes a camp id as an argument.

**Comment by ashish76** [comment]
Based on the discussion we had on Thursday's call (10-Aug-2023),

- There will be only one topic that will be marked as a Hot topic.
- Also there should be a provision for Admin to configure the Hot Topic component as per their choice. Admin should configure the 
1. Title of the hot topic (Mandatory)
2. Description of the hot topic (Mandatory, we will decide the character limit)
3. Upload image (Optional)
4. Link to the topic (Mandatory)

Please update if any other information is to be added.

There will be only one configuration in the database for hot topics. Any modification will update the existing configuration.

@BrentAllsop , @mark-shamy & @CanonizerJim Please validate.

**Comment by kellycasa1** [comment]
This looks good!

**Comment by sajid315** [comment]
@BrentAllsop 
Do we need to maintain history of hot topics ?  
Because according to above confirmation we only need one configuration for hot topic that will be updated each time when changed by admin.

**Comment by rupalichavan9860** [comment]
@ashish76 Please check test cases below : 
### **General Test cases:** 

UI Field Test Cases : 
1. Check the field design should be as per the customer’s specification
2. The field layout should be as per the customer’s specifications.
3. Check if the fields are mandatory. Then red ” * ” should be displayed.
4. Check whether placeholder text should be shown properly or not for the fields.
5. Check the width and height of the fields

Functional Test Cases for the text fields : 
1. Check when the user clicks on the  field, the text cursor should be visible in the specific field.
2. Check whether the user can click on the field or not.
3. Check whether the user can type in the field or not.
4. Check the user can copy text from the field.
5. Check the user can remove text from the field.
6. Check the maximum and minimum length of characters in the field.
7. Check length with boundary values in the field.
8. Check whether the user should be able to leave a blank field.
9. Check whether entered values should be properly visible or not.
10. Check if the field allows Blank Inputs.
11. Check if the text field is allowing trailing spaces or leading spaces.
12. Check the text field is allowing copy-paste.
13. Check if the field allows spaces.
14. Check default text is displaying inside the text area.
15. Check on clicking inside the text area the default text should not display.

Test Case For Mandatory Fields : 
1. Check if the mandatory fields of the application are marked with a special character like a red star icon (*).
2. Try to save the mandatory field without entering any data on the fields.
3. Check for the alert/error message when submitting the form without filling in the mandatory field.
4. Check if the proper alert/error message is displaying or not.
5. Check the field’s behavior when the user tries to submit the form without filling in the mandatory field.
6. Check if the valid values are saved on the mandatory field after clicking the save or submit button.
7. Check if the alert message displays when the user edits a mandatory field and leaves that mandatory field blank.
8. Check for the alert message when the user submits the form by filling in some mandatory fields, but still, some are blank.
9. Check if the user is saved mandatory fields by putting spaces.
10. Check if the alert/error message displays when the user tries to paste unaccepted values.

Test Cases For Dropdown : 
1. Check whether the dropdown is clickable or not.
2. Check if the drop-down is open by clicking on both the drop-down & the drop-down Arrow.
3. Verify that when the user clicks on the drop down list then all options should be displayed in the list
4. Verify that if the drop down is a mandatory field then a validation error message should be displayed
5. Verify that if the drop down is the mandatory field then a red “*” mark should be displayed.
6. Verify that order of the values in the drop down list
7. Verify that the user is able to scroll down in the drop down field or not
8. Verify that the user should not be able to edit in the drop down list field
9. Verify that the user should not be select more than one option from the drop down list
10. Check that the dropdown values should be accessible and selected by clicking on the alphabet from the keyboard.
11. Check dropdown list design should not be disturbed on all browsers.

Test cases for Upload image : 
1. Verify Upload Image button is clickable or not.
2. Verify upload image/file popup is open or not by clicking on the upload image button.
3. Verify by clicking on the cancel button upload image popup closed or not.
4. Check image upload functionality with image files of different extensions (e.g. JPEG, PNG, BMP etc.)
5. Check image upload with image size greater than the max allowed size. The Proper error message should be displayed.
6. Check image upload functionality with file types other than images (e.g. txt, doc, pdf, exe etc.). A proper error message should be displayed.
7. Check if images of specified height and width (if defined) are accepted otherwise rejected.
8.  The image upload progress bar should appear for large size images.
9. Check if cancel button functionality is working in between upload process.
10. Check image quality after upload. Image quality should not be changed after upload.

### **Functional Test cases (Hot Topic- Admin) :** 
1. Only Admin users can configure the Hot Topic component 
2. There will be only one topic that will be marked as a Hot topic.
3. Admin can configure hot topic with below fields : 

- 	Title of the hot topic (Mandatory)
- 	Topic dropdown
- 	Camp dropdown
- 	Description of the hot topic (Mandatory)
- 	Upload image (Optional)
- 	Link to the selected topic/camp (Mandatory)
- 	Submit button
- 	Publish button

- List of hot topics with 3 different sections :Live (Green),In Review (Yellow),Archived (Blue) with Edit and Publish/Republish options

4. Admin user should able to edit, preview and publish the hot topics
5. On Submit, the topic will be stored as in-review state.
6. When user clicks on the Publish button, a preview will be shown to the user, and on the confirmation, the topic will be marked as published(Live-green).
7. Once the user has published the topic, any earlier topics will be archived (Blue).

Test Cases For Topic Dropdown :  

1. Verify that only active topics are listed (do not include Archived topics).
2. Verify that the topic names listed are live names.

Test Cases For Camp Dropdown : 

1.  Verify that the data in the camp drop down list is accurately listed based on the value selected from the topic drop down.
2. Verify that only active camps are listed (do not include Archived camps).
3. Verify that the camp names listed are live names.
