### ISSUE TITLE
Camp Breadcrumb missing in specific case

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#727]
Go to any topic or a specific one like below:
https://canonizer3.canonizer.com/topic/88-Theories-of-Consciousness/1-Agreement

1. Open the "Event line" for the topic.
2. Play the timeline to a specific camp creation, e.g. : inner camp number 5 or 6 so on.
3. Now the events coming to left panel.
4. Click on the camp creation event that made by any nickname.
5. On opening of event link it redirects to the topic detail page.

Issue:
Camp breadcrumb is missing for camp, also the camp URL not including the camp name.

![is1](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/83af6b1a-062b-4652-a755-d49e02fa29c2)

**Comment by sajid315** [comment]
As per the discussion on this issue with @sunilspr7 in skype call, the timeline event API response key used on front end is wrong. We need to utilize the "url" key in response instead of "camp_id". And this issue ll be resolved after completion of following ticket, because there is no issue found related to epoch time in it. 
https://github.com/the-canonizer/canonizer-service/issues/237

**Comment by hassaanCD** [comment]
Fixed


![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/ffb64ba9-53cd-42f3-aea4-1088b70f2fc4)

**Comment by sandeeptlgt** [comment]
Closed

**Comment by rupalichavan9860** [comment]
Verified on live
