### ISSUE TITLE
Camps are not showing in main page "Recent Activities"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#771]
Camps are not showing in main page "Recent Activities" as shown in attached screenshot below

![Image](https://user-images.githubusercontent.com/120023458/267701977-4ab2ac04-db36-4746-8cbc-8b0660235183.png)

**Comment by sajid315** [comment]
@rupalichavan9860 we need to confirm this ticket from your end. As ticket describing that camp created activity should b shown on home page activities.
So this is due to because on creation of new Camp the user is not direct supporter of it. Anyhow other proposed change activities in camp is already showing in list. 
Do we need to proceed on it ?

**Comment by rupalichavan9860** [comment]
This is working fine as per requirements so closing this
