### ISSUE TITLE
Search is not working on production

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#909]
As shown in attached screenshots:

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/99f37b3c-c3cd-43d7-b72b-ff666be043ac)

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/f7eff1f8-5ec1-4bca-b497-aa582b490372)

**Comment by nalwa** [comment]
I reviewed this issue and found search is working now it might be due to some server configuration or due code deployment going on that time.  

But, its still not working correctly as on development and staging for that we have another ticket 
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/761

@hassaanCD  please verify.

**Comment by hassaanCD** [comment]
Verified on production

**Comment by rupalichavan9860** [comment]
This is working fine on production
